apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: lead-framework
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    profiles:
    - schedulerName: lead-scheduler
      plugins:
        filter:
          enabled:
          - name: LEADPlugin
        score:
          enabled:
          - name: LEADPlugin
          disabled:
          - name: NodeResourcesFit
      pluginConfig:
      - name: LEADPlugin
        args:
          leadFramework: enabled
    leaderElection:
      leaderElect: true
      resourceName: lead-scheduler
      resourceNamespace: kube-system
    metricsBindAddress: 0.0.0.0:10259
    healthzBindAddress: 0.0.0.0:10259
