apiVersion: apps/v1
kind: Deployment
metadata:
  name: lead-net-affinity
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lead-net-affinity
  template:
    metadata:
      labels:
        app: lead-net-affinity
    spec:
      serviceAccountName: lead-net-affinity
      containers:
        - name: controller
          image: moein81/lead-net-affinity:0.1.3
          env:
            - name: LEAD_NET_CONFIG
              value: /etc/lead-net-affinity/config.yaml
            - name: LEAD_NET_LOG
              value: debug
            - name: LEAD_NET_DRYRUN
              value: "false"
          volumeMounts:
            - name: cfg
              mountPath: /etc/lead-net-affinity
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      volumes:
        - name: cfg
          configMap:
            name: lead-net-affinity-config
